### ISSUE TITLE
Merging repoes?

### ISSUE THREAD

**Issue by mhaamann** [nielsgl/sequelize-paper-trail#4]
Hi @nielsgl 

Are you interested in merging repoes? I just forked your package the other day and updated the code quite a lot. I'm not sure if I am working in the same direction as you wanted to.

New features I added:
* Full continuation-local-storage support (solves #2)
* MySQL support (Postgres is also still supported)
* Option to disable the change model since it can generate a lot of unneeded data depending your use case.
* Added a simple migration example. (solves #3)

I will be adding tests soon.

**Comment by nielsgl** [comment]
Hey @mhaamann 

Sounds great! I started this project because there wasn't anything out there that was actively maintained. Last few weeks I was a bit busy with work and I actually started last weekend on solving the open issues, but feel free to send me a pull request and I'd be happy to merge it in!

Let's make it awesome :)

**Comment by mhaamann** [comment]
Great! Maybe we should agree on which direction we want to go. Maybe a todo list?

Created a PR. There is a lot of changes. I am open for changes. I didn't have any guidelines to follow so I just tried to keep the same style while keeping the changes to the documentation at a minimum.

**Comment by nielsgl** [comment]
Merged :)
