### ISSUE TITLE
Discussion, previousVersion or currentVersion?

### ISSUE THREAD

**Issue by mhaamann** [nielsgl/sequelize-paper-trail#6]
Right now the module saves the **currentVersion** in the document attribute of RevisionModel.

Why not save the **previousVersion** instead?

Consider the following code example:

```
# Current User object in DB:
{id: 4, firstName: 'Jonn', lastName: 'Dot'}

# Update to the user:
models.user.findOne({where: {id: 4}}).then(function (userFromDB) {
  return userFromDB.update({firstName: 'JonA', lastName: 'Doe'});
});
--
# Update to the user:
models.user.findOne({where: {id: 4}}).then(function (userFromDB) {
  return userFromDB.update({firstName: 'John'});
});
--
# Update to the user:
models.user.findOne({where: {id: 4}}).then(function (userFromDB) {
  return userFromDB.update({firstName: 'JohnB'});
});
--
# Update to the user:
models.user.findOne({where: {id: 4}}).then(function (userFromDB) {
  return userFromDB.update({lastName: 'DoT'});
});
```

The RevisionModel now contains ('currentVersions') in the document colum:
{id: 4, firstName: 'Jonn', lastName: 'Dot', revision: 1} // Initial Create
{id: 4, firstName: 'JonA', lastName: 'Doe', revision: 2} // Update
{id: 4, firstName: 'John', revision: 3}
{id: 4, firstName: 'JohnB', revision: 4}
{id: 4, lastName: 'DoT', revision: 5}

Having identified my spelling mistake I would now like to revert the user object back when the user was called _John Doe_.
With the current implementation of paper-trail we would have to replay the revision log backwards until we reach revision 3.
Quite a risky task.

Instead I suggest that we instead store the **previousVersion** instead. Doing this the RevisionModel from the above example will end up looking like this:
{} // Initial Create
{id: 4, firstName: 'Jonn', lastName: 'Dot', revision: 1}
{id: 4, firstName: 'JonA', lastName: 'Doe', revision: 2}
{id: 4, firstName: 'John', lastName: 'Doe', revision: 3}
{id: 4, firstName: 'JohnB', lastName: 'Doe', revision: 4}

This way it is very easy to revert back to a revision since it contains the full object. The only requirement is that a fully loaded object is used when updating something.

Does that make sense?

**Comment by mhaamann** [comment]
The down side is that you loose track on who did the change and without the RevisionChangeModel you cannot see what was updated. This is also bad :(

What if we introduce a new coloum 'snapshot' where the previousVersion is stored. The 'currentVersion' will still be stored in document. 
We could furthermore improve paper-trail by loading the full object from db automatically for the snapshot instead of relying that previousVersion actually contains a fully loaded object. 

At least in our codebase we have a lot of places where we load an object and only specify 1-2 attributes instead of fully loading all attributes.

**Comment by nielsgl** [comment]
Yeah there are arguments to do it either way. The downside of storing {} as initial state is that it doesn't add much value because when a model is created we would immediately need to add 2 rows in the Revisions table, one with {} and one with the model as it is when it is created.
Currently, the Revisions table already contains the full model at each step in the document column, so when I create a user, say {first_name: 'John', last_name: 'Doe'} it will contain the full model will be stored there as revision 1, and when I update the first name of the user, a row is added to the revisions table and then the document column contains the new model, say {first_name: 'Jane', last_name: 'Doe'} and the RevisionChanges will have a row where path = 'first_name', document will contain the previous and current values, so both 'John' and Jane' and will be associated with Revision id = 2, this enables us to actually search for every snapshot in which the first_name was either 'John' and it was updated to something else (lhs: 'John') or when it was something else and updated to 'John' (rhs: 'John')
